### ISSUE TITLE
Env variable BROWSERSTACK_APP_ID not set

### ISSUE THREAD

**Issue by michelle-chiang** [browserstack/browserstack-fastlane-plugin#15]
The logs say that the app binary was successfully uploaded to Browserstack and that the environment variable was set, but the environment variable is actually missing.

In my Fastfile:
```
build_app(
      workspace: "./ios/x1.xcworkspace", 
      scheme: "x1",
      destination: "generic/platform=iOS",
      sdk: "iphoneos",
      export_options: {
        method: "development"
      }
    )
    upload_to_browserstack_app_automate(
      browserstack_username: ENV["BROWSERSTACK_USERNAME"],
      browserstack_access_key: ENV["BROWSERSTACK_ACCESS_KEY"]
    )
```

Logs:
```
[17:22:52]: Uploading app to BrowserStack AppAutomate...
[17:22:56]: Successfully uploaded app <path-to-ipa> to BrowserStack AppAutomate with app_url : <app_url>
[17:22:56]: Setting Environment variable BROWSERSTACK_APP_ID = <app_url>
```

After:
```
$ echo $BROWSERSTACK_APP_ID

```
Nothing appears and I can't use `BROWSERSTACK_APP_ID` in scripts.

**Comment by gshah30** [comment]
Hi @michelle-chiang ,

The environment variable set in the fastlane plugin is not supposed to be accessible in the terminal. It will be accessible only in the lane in the fastfile in which the environment variable was set up.

So for example, in [this sample code](https://github.com/browserstack/browserstack-android-sample-app/blob/c9b8ea057675bd01c83735476f3b52e98eadc9e5/fastlane/Fastfile#L19), the environment variable was set in the action `upload_to_browserstack_app_automate` which is present in the lane `upload_test`, so the the environment variable will be accessible only in an action in this lane. Thus, it will also be accessible in the `gradle(task: "test")` (the mobile app test script).

Please let us know if the environment variable is not accessible in the fastlane lane.

Thanks.
